config/routes.rb
Rails.application.routes.draw do

  get '/dashboard', to:'home#dashboard'

  resources :rankings, only: [:index]

  resources :likes, only: [:destroy,:create,:index]

  resources :dictionaries do
    collection do
      delete 'destroy_multiple'
      post 'create_multiple'
    end
  end
  resources :words do
    resources :meanings, only:[:new, :create]
  end

  resources :meanings, except:[:new, :create,:show]  do
    resources :examples, only:[:new,:create,:destroy]
    member do
      get 'meaning_examples'
    end
  end

  resources :dictionaries, only:[:new,:create,:destroy]

  resources :users, only: [:show,:index] do
    collection do
      get 'dictionary'
    end
  end



  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dictionary.rb
class Dictionary < ApplicationRecord
  belongs_to :user
  belongs_to :meaning

  validates :meaning_id, :uniqueness => {:scope => :user_id}

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << csv_column_names
      all.each do |dictionary|
        csv << dictionary.csv_column_values
      end
    end
  end

  def self.csv_column_names
    ["単語","意味"]
  end

  def csv_column_values
    [meaning.word.english_word, meaning.meaning]
  end



end

app/models/example.rb
class Example < ApplicationRecord
  belongs_to :meaning
  belongs_to :user
  has_many :likes, :dependent => :destroy
end

app/models/guest_user.rb
class GuestUser < User
  attr_accessor :nick_name, :email, :id
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :example

  validates :example_id, :uniqueness => {:scope => :user_id}
end

app/models/meaning.rb
class Meaning < ApplicationRecord
  belongs_to :word
  has_many :dictionaries
  has_many :examples, :dependent => :destroy
  validates_presence_of :meaning
  validates :meaning, :uniqueness => {:scope => :word_id}

end

app/models/user.rb
class User < ApplicationRecord
  ############################################################################################
  ## PeterGate Roles                                                                        ##
  ## The :user role is added by default and shouldn't be included in this list.             ##
  ## The :root_admin can access any page regardless of access settings. Use with caution!   ##
  ## The multiple option can be set to true if you need users to have multiple roles.       ##
  petergate(roles: [:admin, :editor], multiple: false)                                      ##
  ############################################################################################

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :nick_name
  has_many :examples

  has_many :dictionaries
  has_many :likes

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << csv_column_names
      all.each do |dictionary|
        csv << dictionary.csv_column_values
      end
    end
  end

  def self.csv_column_names
    ["単語","意味"]
  end

  def csv_column_values
    [meaning, meaning.meaning]
  end



end

app/models/word.rb
class Word < ApplicationRecord
  validates :english_word, uniqueness: true
  has_many :meanings, :dependent => :destroy

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << csv_column_names
      all.each do |dictionary|
        csv << dictionary.csv_column_values
      end
    end
  end

  def self.csv_column_names
    ["単語","意味"]
  end

  def csv_column_values
    [meaning.word.english_word, meaning.meaning]
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  access all: [:index], user: {except: [:destroy,:new,:create, :update, :edit, :toggle_status]}, site_admin: :all
  def index
    @words = Word.all

    @words = @words.eager_load(:meanings).where(meanings: {level: params[:level].to_i}) if params[:level].present?
    @words = @words.eager_load(:meanings).where(meanings: {toeic: params[:toeic].to_i}) if params[:toeic].present?

    @words = @words.where(english_word: params[:english_word]) if params[:english_word].present?
    @words = @words.eager_load(:meanings).where(meanings: {meaning: params[:meaning]}) if params[:meaning].present?
    @words = @words.eager_load(:meanings).where(meanings: {parse: params[:parse]}) if params[:parse].present?

    #@meanings = Meaning.all
    #@meanings = @meanings.eager_load(:word).where(word: {english_word: params[:english_word]}) if params[:english_word].present?
    #@meanings = @meanings.where(meaning: params[:meaning]) if params[:meaning].present?
    @dictionary = Dictionary.new
    @like = Like.new
  end

  def dashboard
    @users = User.all
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def index
  end

  def create
    @like = Like.new(like_params)
    if @like.save
      redirect_to request.referrer, notice: 'Like was successfully created.'
    else
      redirect_to request.referrer, alert: 'Like failed to save'
    end
  end

  def destroy
  end

  private
    def like_params
      params.require(:like).permit(:example_id, :user_id).merge(voter: current_user.id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user_posts = current_user.examples
  end

  def index
    @users = User.all
  end

  def dictionary
    @user_dictionary = current_user.dictionaries

    @user_dictionary = current_user.dictionaries if params[:c] == "all"
    @user_dictionary = @user_dictionary.eager_load(:meaning).where('toeic IS NOT NULL') if params[:c] == "toeic"

    bom = "\xFF\xFE".force_encoding("UTF-16LE")
    respond_to do |format|
      format.html
      format.js
      format.csv { send_data bom + @user_dictionary.to_csv.encode("UTF-16LE"), filename: "vocabuil.csv" }
      format.xls { send_data bom + @user_dictionary.to_csv(col_sep: "\t").encode("UTF-16LE") }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def login_helper style = ''
    if current_user.is_a?(GuestUser)
      (link_to "Register", new_user_registration_path, class: style) +
      " ".html_safe +
      (link_to "Login", new_user_session_path, class: style)
    else
      (link_to "Logout", destroy_user_session_path, method: :delete, class: style) +
      " ".html_safe +
      (link_to "マイページ", user_path(current_user), class: style)
    end
  end


  def nav_items
    [
      {
        url: dictionary_users_path,
        title: '単語帳'
      },
      {
        url: dictionary_users_path,
        title: '単語帳'
      }
    ]
  end

  def nav_helper style
    nav_links = ''

    nav_items.each do |item|
      nav_links << "<a href='#{item[:url]}' class='#{style}'>#{item[:title]}</a>"
    end

    nav_links.html_safe

  end

  def parts
    [1,2,3,4,5]
  end

  def levels
    ["初級","中級","上級"]
  end

  def side_bar_helper
    sidebars = ''
    i = 1

    levels.each do |level|
      sidebars << "<div class='collapse text-center' id='menu#{i.to_s}'>
        <a href='#menu#{i.to_s}sub#{i.to_s}' class='list-group-item list-group-item-action' data-toggle='collapse' aria-expanded='false'> #{level}</a>"
        parts.each do |part|
        "<div class='collapse' id='menu#{i.to_s}sub#{i.to_s}'>
            <a href='#' class='list-group-item list-group-item-action' data-parent='menu#{i.to_s}'>#{part}</a>
        </div>"
        end
        "</div>"
        i += 1
    end

    sidebars.html_safe

  end

  def example_creation_button_toggle_helper object
    max_example_numbers = 5

    if object.examples.count.to_i > max_example_numbers
      link_to "例文作る" , "#{request.url}", class: "btn btn-secondary disabled"
    else
      link_to "例文作る" , new_meaning_example_path(object.id), class: "btn btn-warning text-white"
    end

  end


end

app/helpers/dictionaries_helper.rb
module DictionariesHelper
end

app/helpers/examples_helper.rb
module ExamplesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/meanings_helper.rb
module MeaningsHelper
end

app/helpers/rankings_helper.rb
module RankingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlashCard</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user.has_roles?(:admin) %>
    <%= render "shared/admin_nav" %>
    <% end %>
    <%= render "shared/nav-bar" %>
    <%= render "shared/sub_nav_bar" %>
    <%= render "shared/notification_bar.html.erb" %>
    <div style="height: 110rem;">
    <%= yield %>
    </div>


  <section id="alphabet" class="row bg-light">
  <div class="container py-2">
    <%
      ary = []
      ('a'..'z').each do |i|
        ary.push(i.to_s)
      end %>
    <% ary.each do |a| %>
    <div class="float-left px-1">
      <button type="button" class="btn btn-primary circle-btn">
      <%= a %>
      </button>
    </div>
    <% end %>
  </div>
  </section>

  <%= render "shared/main_footer" %>



  </body>
</html>

app/views/shared/_admin_nav.html.erb
<nav class="navbar navbar-expand-sm navbar-dark bg-dark p-0">
    <div class="container">
      <%=link_to "Yusuke", root_path, class: "navbar-brand"%>
      <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarNav">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item px-2">
            <a href="index.html" class="nav-link active">Dashboard</a>
          </li>
          <li class="nav-item px-2">
            <a href="posts.html" class="nav-link">Posts</a>
          </li>
          <li class="nav-item px-2">
            <a href="categories.html" class="nav-link">Categories</a>
          </li>
          <li class="nav-item px-2">
            <a href="users.html" class="nav-link">Users</a>
          </li>
        </ul>

        <ul class="navbar-nav ml-auto">
          <li class="nav-item dropdown mr-3">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-user"></i> Welcome Yusuke
            </a>
            <div class="dropdown-menu">
              <a href="profile.html" class="dropdown-item">
                <i class="fa fa-user-circle"></i> Profile
              </a>
              <a href="settings.html" class="dropdown-item">
                <i class="fa fa-gear"></i> Settings
              </a>
            </div>
          </li>
          <li class="nav-item">
            <a href="login.html" class="nav-link">
              <i class="fa fa-user-times"></i> Logout
            </a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

app/views/shared/_dashboard_table_user.html.erb
<table class="table table-hover">
<thead>
  <tr>
    <th>#</th>
    <th>Name</th>
    <th>Email</th>
    <th>Role</th>
    <th>編集</th>
  </tr>
</thead>
<tbody>
  <% @users.each do |user| %>
  <tr>
    <td scope="row"><%= user.id %></td>
    <td><%= user.nick_name %></td>
    <td><%= user.email %></td>
    <td><%= user.roles[0] %></td>
    <td><%= link_to cancel_user_registration_path(user.id) %></td>
  </tr>
   <% end %>
</tbody>
</table>

app/views/shared/_main_footer.html.erb
<footer id="footer" class="footer bg-dark text-white">
  <div class="container">
    <div class="row">
      <div class="col text-center">
        <div class="py-4">
          <h1 class="h3">FlashCard.com</h1>
          <p>Copyright &copy; 2017 </p>
          <button class="btn btn-primary" data-toggle="modal" data-target="#contactModal">Contact Us</button>
        </div>
      </div>
    </div>
  </div>
</footer>

<div class="modal fade text-dark" id="contactModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="contactModalTitle">Contact Us</h5>
        <button class="close" data-dismiss="modal"><span>&times;</span></button>
      </div>
      <div class="modal-body">
        <form>
          <div class="form-group">
            <label for="name">Name</label>
            <input type="text" class="form-control">
          </div>
          <div class="form-group">
            <label for="email">Email</label>
            <input type="text" class="form-control">
          </div>
          <div class="form-group">
            <label for="name">Message</label>
            <textarea class="form-control"></textarea>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button class="btn btn-primary btn-block">Submit</button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_nav-bar.html.erb
<nav id="home-nav" class="navbar navbar-expand-sm">
<div class="container">
  <div class="navbar-brand__wrapper">
    <%= link_to  root_path, class: "navbar-brand site-name" do %>
      <span class="navbar-brand">仮</span>
      <span class="nav-brand__span">.com</span>
    <% end %>
  </div>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <div class="navbar-nav ml-auto nav-bar-items">
    <% if current_user.is_a?(GuestUser)
       %>
    <% else %>
      <%= nav_helper 'btn btn-outline-primary mb-auto btn-original' %>
    <% end %>
      <%= login_helper 'btn btn-outline-primary btn-original'%>
    </div>
  </div>
</div>
</nav>

app/views/shared/_notification_bar.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success alert-dismissible fadeshow">
  <button class="close" data-dismiss="alert" type="button">
    <span>&times;</span>
  </button>
    <%= flash[:notice] %>
  </div>
<% end %>
<% if flash[:alert] %>
  <div class="alert alert-danger alert-dismissible fadeshow">
  <button class="close" data-dismiss="alert" type="button">
    <span>&times;</span>
  </button>
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/shared/_root-search.html.erb
<% @parse = ["動","形動"] %>
<div class="search-root">
<div class="search-root__wrapper">
<%= form_tag root_path, method: :get do %>
<%= hidden_field_tag :level, params[:level] %>
<%= hidden_field_tag :toeic, params[:toeic] %>
<%= text_field_tag :english_word, params[:english_word], placeholder: "単語", class: "search-root__wrapper__input input-word" %>
<%= text_field_tag :meaning, params[:meaning], placeholder: "意味", class: "search-root__wrapper__input input-meaning" %>
<%= select_tag :parse, options_for_select([["品詞", ""], ["動詞", "動"],["形容動詞","形動"]], { selected: "" }),  :include_blank => true, class: "search-root__wrapper__select" %>
<%= submit_tag "Search", name: nil, class: "search-root__wrapper__button" %>
<% end %>
</div>
</div>

app/views/shared/_side_bar.html.erb
<% @part = [1,2,3,4,5] %>
<% @level = ["begginer","novice","A beginner","intermediate","A intermediate","advanced","proficient","expert","scholar"] %>
<% @toeics = [400,600,800] %>

<nav class="sidebar">
    <div class="sidebar__level">
        <ul class="sidebar__level__list">
        <% active = params[:level] == nil || params[:level].empty? ? 'active' : '' %>
        <li class="sidebar__level__list__item <%= active %>">
          <%= link_to "LEVEL" ,root_path, class: "#{active} sidebar__level__list__item__title" %><span class="badge badge-secondary ml-2 align-center"><%= Word.count %></span>
        </li>
        <% @level.each.with_index(1) do |level,i| %>
          <% active = params[:level].to_i == i ? 'active' : '' %>
          <li class="sidebar__level__list__item <%= active %>"><span><%= link_to "#{level}" ,root_path(level: i), class: "#{active} sidebar__level__list__item__link" %></span><span class="badge badge-secondary ml-2 align-center"><%=  Word.eager_load(:meanings).where(meanings: {level: i.to_i}).count %></span></li>
        <% end %>
        </ul>
    </div>

    <div class="sidebar__toeic">
        <ul class="sidebar__level__list">
        <% active = params[:toeic] == nil || params[:toeic].empty? ? 'active' : '' %>
        <li class="sidebar__level__list__item <%= active %>">
          <%= link_to "TOEIC" ,root_path(toeic: ""), class: "#{active} sidebar__level__list__item__title" %><span class="badge badge-secondary ml-2 align-center"><%= Word.count %></span>
        </li>
        <% @toeics.each.with_index(1) do |toeic,i| %>
          <% active = params[:toeic].to_i == i ? 'active' : '' %>
          <li class="sidebar__level__list__item <%= active %>"><span><%= link_to "#{toeic}" ,root_path(toeic: i), class: "#{active} sidebar__level__list__item__link" %></span><span class="badge badge-secondary ml-2 align-center"><%=  Word.eager_load(:meanings).where(meanings: {toeic: i.to_i}).count %></span></li>
        <% end %>
        </ul>
    </div>
</nav>

app/views/shared/_sub_nav_bar.html.erb
<nav class="nav navbar-dark bg-dark">
  <%= link_to "単語一覧", words_path, class: "nav-link " %>
  <%= link_to "単語追加", new_word_path, class: "nav-link " %>
  <%= link_to "意味一覧",  meanings_path, class: "nav-link " %>
  <%= link_to "ランキング",  rankings_path, class: "nav-link " %>
  <%= link_to "ダッシュボード",  dashboard_path, class: "nav-link " %>
  <% if current_user.has_roles?(:admin) %>
  <%= link_to "ユーザー一覧",  users_path, class: "nav-link " %>
  <% end %>
</nav>

app/views/shared/_table.html.erb
<table class="table table-hover table-sm">
 <%= simple_form_for(@dictionary) do |f|  %>
  <thead>
    <tr>
      <% if current_user.has_roles?(:admin) %>
      <th>#</th>
      <th>#</th>
      <% end %>
      <th width="12%">英語</th>
      <th width="12%">意味</th>
      <th width="5%">品詞</th>
      <th width="30%">例文</th>
      <th class="example-index" width="5%"></th>
      <th class="create-example" width="5%"></th>
      <% unless current_user.is_a?(GuestUser) %>
      <th class="add-dictionary" width="5%"></th>
      <th class="add-dictionary" width="5%"><%= f.submit '追加', :class => 'btn btn-primary'  %></th>
      <% end %>
      <% if current_user.has_roles?(:admin) %>
      <th>toeic</th>
      <th>英検</th>
       <% end %>
    </tr>
  </thead>

  <tbody>
    <% @words.each do |word| %>
    <% word.meanings.each do |meaning| %>
      <tr>
        <% if current_user.has_roles?(:admin) %>
      　<td><%= meaning.word.id %></td>
        <td><%= meaning.id %></td>
        <% end %>
        <td width="12%"><%= meaning.word.english_word %></td>
        <td width="12%"><%= meaning.meaning %></td>
        <td width="5%"><%= meaning.parse %></td>
        <td width="25%">
        <% meaning.examples.first(1).each do |meaning_example| %>
        <%= meaning_example.sentence.capitalize  %><br>
        <%= meaning_example.translation %><br>
        <% end %>
        </td>
        <td  width="5%"><%= link_to "一覧", meaning_examples_meaning_path(meaning.id) , class: "btn btn-primary" %></td>
        <td width="5%">
          <%= example_creation_button_toggle_helper meaning %>
        </td>
        <% unless current_user.is_a?(GuestUser) %>
        <%= simple_form_for(@dictionary) do |f|  %>
        <td width="3%">
          <%if Dictionary.where(user: current_user).where(meaning_id: meaning.id).present? %>
          <i class="fa fa-book fa-book-existed" aria-hidden="true" data-toggle="tooltip" data-placement="right" title="追加済み">
          <% else %>
          <div style="display: inline-block;"><%= f.input :meaning_id, :as => :hidden, :input_html => { :value => meaning.id } %>
          <%= button_tag(type: 'submit', class: "btn btn-link") do %><i class="fa fa-book" aria-hidden="true" data-toggle="tooltip" data-placement="right" title="単語帳に追加"></i><% end %>
          <% end %></div>
        </td>
        <% end %>
        <% end %>

        <td width="5%"><%= f.check_box :meaning_id,collection: meaning.id, class:"tag-chack-box" %>

        <% if current_user.has_roles?(:admin) %>
        <td><%= meaning.toeic %></td>
        <td><%= meaning.toeic %></td>
        <td><%= meaning.eiken %></td>
        <td><%= link_to 'Edit', edit_meaning_path(meaning.id) %></td>
        <td><%= link_to 'Destroy', meaning_path(meaning.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
         </td>
      </tr>
    <% end %>
    <% end %>
  </tbody>
<% end %>
</table>

app/views/shared/_user-sidebar.html.erb
<nav class="side-bar_user">
  <ul class="side-bar_user-nav">
    <li class="side-bar_user-nav__root"><%= link_to root_path , class: "side-bar_user-nav__link" do %><span class="side-bar_user-nav__icon"><span>かり</span><span>.com</span><% end %></li>
    <li class="side-bar_user-nav__item"><%= link_to user_path(current_user), class: "side-bar_user-nav__link" do %><span class="side-bar_user-nav__icon"><i class="fa fa-graduation-cap" aria-hidden="true"></i></span>PROF<% end %></li>
    <li class="side-bar_user-nav__item"><%= link_to user_path(current_user), class: "side-bar_user-nav__link" do %><span class="side-bar_user-nav__icon"><i class="fa fa-graduation-cap" aria-hidden="true"></i></span>SENTENCE<% end %></li>
    <li class="side-bar_user-nav__item"><%= link_to user_path(current_user), class: "side-bar_user-nav__link" do %><span class="side-bar_user-nav__icon"><i class="fa fa-usd" aria-hidden="true"></i></span>POINT<% end %></li>
  </ul>
  <ul class="side-bar_user-nav-bottom">
    <li class="side-bar_user-nav__bottom-item"><%= link_to user_path(current_user), class: "side-bar_user-nav__link" do %><span class="side-bar_user-nav__icon"><i class="fa fa-cog" aria-hidden="true"></i></span>setting<% end %></li>
      <li class="side-bar_user-nav__bottom-item"><%= link_to destroy_user_session_path, method: :delete, class: "side-bar_user-nav__link" do %><span class="side-bar_user-nav__icon"><i class="fa fa-sign-out" aria-hidden="true"></i></span>LOGOUT<% end %></li>
  </ul>
</nav>