config/routes.rb
Rails.application.routes.draw do

  get '/dashboard', to:'home#dashboard'

  resources :rankings, only: [:index]

  resources :likes, only: [:destroy,:create,:index]

  resources :dictionaries do
    collection do
      delete 'destroy_multiple'
      post 'create_multiple'
    end
  end
  resources :words do
    resources :meanings, only:[:new, :create]
  end

  resources :meanings, except:[:new, :create,:show]  do
    resources :examples, only:[:new,:create,:destroy]
    member do
      get 'meaning_examples'
    end
  end

  resources :dictionaries, only:[:new,:create,:destroy]

  resources :users, only: [:show,:index] do
    collection do
      get 'dictionary'
    end
  end



  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/word.rb
class Word < ApplicationRecord
  validates :english_word, uniqueness: true
  has_many :meanings, :dependent => :destroy

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << csv_column_names
      all.each do |dictionary|
        csv << dictionary.csv_column_values
      end
    end
  end

  def self.csv_column_names
    ["単語","意味"]
  end

  def csv_column_values
    [meaning.word.english_word, meaning.meaning]
  end

end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_word, only: [:show, :edit, :update, :destroy]
  access all: [:index, :show, :new, :edit, :create, :update, :destroy], user: :all

  # GET /words
  def index
    @words = Word.all
  end

  # GET /words/1
  def show
  end

  # GET /words/new
  def new
    @word = Word.new
    @meaning = Meaning.new
  end

  # GET /words/1/edit
  def edit
  end

  # POST /words
  def create
    @word = Word.new(word_params)

    if @word.save
      redirect_to @word, notice: 'Word was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /words/1
  def update
    if @word.update(word_params)
      redirect_to @word, notice: 'Word was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /words/1
  def destroy
    @word.destroy
    redirect_to words_url, notice: 'Word was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_word
      @word = Word.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def word_params
      params.require(:word).permit(:english_word)
    end
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/words/_form.html.erb
<div class="container">
<%=  simple_form_for @word  do |f| %>
  <% if @word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@word.errors.count, "error") %> prohibited this word from being saved:</h2>

      <ul>
      <% @word.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.input :english_word %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/words/edit.html.erb
<h1>Editing Word</h1>

<%= render 'form', word: @word %>

<%= link_to 'Show', @word %> |
<%= link_to 'Back', words_path %>

app/views/words/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Words</h1>

<table>
  <thead>
    <tr>
      <th>English word</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @words.each do |word| %>
      <tr>
        <td><%= word.english_word %></td>
        <td><%= link_to 'Show', word %></td>
        <td><%= link_to 'Edit', edit_word_path(word) %></td>
        <td><%= link_to 'Destroy', word, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to "意味を追加" ,new_word_meaning_path(word.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Word', new_word_path %>

app/views/words/new.html.erb
<%= render 'form' %>

app/views/words/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>English word:</strong>
  <%= @word.english_word %>
</p>

<%= link_to 'Edit', edit_word_path(@word) %> |
<%= link_to 'Back', words_path %>