config/routes.rb
Rails.application.routes.draw do

  get '/dashboard', to:'home#dashboard'

  resources :rankings, only: [:index]

  resources :likes, only: [:destroy,:create,:index]

  resources :dictionaries do
    collection do
      delete 'destroy_multiple'
      post 'create_multiple'
    end
  end
  resources :words do
    resources :meanings, only:[:new, :create]
  end

  resources :meanings, except:[:new, :create,:show]  do
    resources :examples, only:[:new,:create,:destroy]
    member do
      get 'meaning_examples'
    end
  end

  resources :dictionaries, only:[:new,:create,:destroy]

  resources :users, only: [:show,:index] do
    collection do
      get 'dictionary'
    end
  end



  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/example.rb
class Example < ApplicationRecord
  belongs_to :meaning
  belongs_to :user
  has_many :likes, :dependent => :destroy
end

app/controllers/examples_controller.rb
class ExamplesController < ApplicationController
  before_action :set_example, only: [:show, :edit, :update, :destroy]
  access all: [:index, :show, :new, :edit, :create, :update, :destroy], user: :all
  before_action :set_meaning, only: [:new, :create]

  # GET /examples
  def index
    @examples = Example.all
  end

  # GET /examples/1
  def show
  end

  # GET /examples/new
  def new
    @example = Example.new
  end

  # GET /examples/1/edit
  def edit
  end

  # POST /examples
  def create
    @example = Example.new(example_params)
    @example.meaning_id = @meaning.id

    if @example.save
      redirect_to root_path, notice: 'Example was successfully created.'
    else
      redirect_to request.referrer
    end
  end

  # PATCH/PUT /examples/1
  def update
    if @example.update(example_params)
      redirect_to @example, notice: 'Example was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /examples/1
  def destroy
    @example.destroy
    redirect_to examples_url, notice: 'Example was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_example
      @example = Example.find(params[:id])
    end

    def set_meaning
      @meaning = Meaning.find(params[:meaning_id])
    end

    # Only allow a trusted parameter "white list" through.
    def example_params
      params.require(:example).permit(:sentence, :translation, :meaning_id).merge(user_id: current_user.id)
    end
end

app/helpers/examples_helper.rb
module ExamplesHelper
end

app/views/examples/_form.html.erb
<div class="meaning-example-form col-md-12">
  <div class="container">
  <div class="meaning-example">
    <div class="meaning-example-new__panel">
    <%= @meaning.word.english_word %>
    <%= @meaning.meaning %>
    <%= @meaning.parse %>
  </div>

  <div class="meaning-example-new__panel">
    <p>他の例文を見る</p>
    <% @meaning.examples.each do |meaning_example| %>
      <%= meaning_example.sentence.capitalize  %><br>
      <%= meaning_example.translation %><br>
    <% end %>
  </div>

  <div class="meaning-example-new__panel form-panel">
    <%=  simple_form_for @example ,url: meaning_examples_path, method: :post  do |f| %>
      <div class="form-group">
        <%= f.input :sentence, label: "英文を入力してください (先頭を大文字にする必要はない)", placeholder: '(例) You are cute',input_html: { class: 'form_input' } %>
      </div>
      <div class="">
        <%= f.input :translation,label: "翻訳", placeholder: '(例) あなたは可愛い',input_html: { class: 'form_input' } %>
      </div>
      <div class="form-group">
        <%= f.submit "送信", class: "btn btn-primary btn-original"  %>
      </div>

    <% end %>
  </div>
  </div>

</div>

</div>

app/views/examples/edit.html.erb
<h1>Editing Example</h1>

<%= render 'form', example: @example %>

<%= link_to 'Show', @example %> |
<%= link_to 'Back', examples_path %>

app/views/examples/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container-90 mx-auto">
<h1>Examples</h1>
<table class="table table-hover">
  <thead  >
    <tr>
      <th>Sentence</th>
      <th>Translation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @examples.each do |example| %>
      <tr>
        <td><%= example.sentence %></td>
        <td><%= example.translation %></td>
        <td><%= link_to 'Show', example %></td>
        <td><%= link_to 'Edit', edit_example_path(example) %></td>
        <td><%= link_to 'Destroy', example, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Example', new_example_path %>

app/views/examples/new.html.erb
<%= render 'form', object: @example %>

app/views/examples/show.html.erb
<p id="notice"><%= notice %></p>



<% @similar_example.each do |se| %>
<%= se.sentence %>
<% end %>



<%= link_to 'Edit', edit_example_path(@example) %> |
<%= link_to 'Back', examples_path %>