config/routes.rb
Rails.application.routes.draw do

  get '/dashboard', to:'home#dashboard'

  resources :rankings, only: [:index]

  resources :likes, only: [:destroy,:create,:index]

  resources :dictionaries do
    collection do
      delete 'destroy_multiple'
      post 'create_multiple'
    end
  end
  resources :words do
    resources :meanings, only:[:new, :create]
  end

  resources :meanings, except:[:new, :create,:show]  do
    resources :examples, only:[:new,:create,:destroy]
    member do
      get 'meaning_examples'
    end
  end

  resources :dictionaries, only:[:new,:create,:destroy]

  resources :users, only: [:show,:index] do
    collection do
      get 'dictionary'
    end
  end



  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/meaning.rb
class Meaning < ApplicationRecord
  belongs_to :word
  has_many :dictionaries
  has_many :examples, :dependent => :destroy
  validates_presence_of :meaning
  validates :meaning, :uniqueness => {:scope => :word_id}

end

app/controllers/meanings_controller.rb
class MeaningsController < ApplicationController
  before_action :set_meaning, only: [:show, :edit, :update, :destroy, :meaning_examples,:create_meaning]
  access all: [:index, :show, :new, :edit, :create, :update, :destroy], user: :all


  # GET /meanings
  def index
    @meanings = Meaning.all
    @words = Word.all
    @dictionary = Dictionary.new
  end

  # GET /meanings/1

  def make_examples
    @examples = @meaning.examples
    @example = Example.new
  end

  # GET /meanings/new
  def new
    @meaning = Meaning.new
    @word = Word.find(params[:word_id])
  end

  # GET /meanings/1/edit
  def edit
  end

  # POST /meanings
  def create
    @meaning = Meaning.new(meaning_params)
    @word = Word.find(params[:word_id])
    @meaning.word_id = @word.id
    if @meaning.save
      redirect_to root_path, notice: 'Meaning was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /meanings/1
  def update
    if @meaning.update(meaning_params)
      redirect_to root_path, notice: 'Meaning was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /meanings/1
  def destroy
    @meaning.destroy
    redirect_to meanings_url, notice: 'Meaning was successfully destroyed.'
  end

  def meaning_examples
    @example = Example.new
    @examples = @meaning.examples
    @like = Like.new
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meaning
      @meaning = Meaning.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def meaning_params
      params.require(:meaning).permit(:meaning, :word_id,:parse, :level, :eiken, :toeic)
    end
end

app/helpers/meanings_helper.rb
module MeaningsHelper
end

app/views/meanings/_form.html.erb
<div class="container">
<%=  simple_form_for @meaning ,url: word_meanings_path, method: :post  do |f| %>

  <%= @word.english_word %>

  <div class="field">
    <%= f.input :meaning %>
  </div>
  <div class="field">
    <%= f.input :parse %>
  </div>
  <div class="field">
    <%= f.input :level %>
  </div>

  <div class="field">
    <%= f.input :eiken %>
  </div>
  <div class="field">
    <%= f.input :toeic %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/meanings/create_meaning.html.erb
<div class="container">
<%=  simple_form_for @example ,url: examples_path, method: :post  do |f| %>
<form>
  <div class="form-group">
    <%= f.input :sentence, label: "英文を入力してください",html: { class: 'form-control' } %>
  </div>

  <div class="form-group">
    <%= f.input :translation,label: "翻訳した日本語を入力してください", html: { class: 'form-control' } %>
  </div>

  <div class="form-group">
    <%= f.input :meaning_id, as: :hidden,input_html: { value: @meaning.id } %>
  </div>

  <div class="form-group">
    <%= f.submit "送信", class: "btn btn-primary"  %>
  </div>
</form>
<% end %>
</div>

app/views/meanings/edit.html.erb
<h1>Editing Meaning</h1>

<div class="container">
<%=  simple_form_for @meaning ,url: meaning_path, method: :patch  do |f| %>
  <p id="notice"><%= notice %></p>
　<%= @meaning.word.english_word %>

  <div class="field">
    <%= f.input :meaning %>
  </div>
  <div class="field">
    <%= f.input :parse %>
  </div>
  <div class="field">
    <%= f.input :level %>
  </div>

  <div class="field">
    <%= f.input :eiken %>
  </div>
  <div class="field">
    <%= f.input :toeic %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

<%= link_to 'Show', @meaning %> |
<%= link_to 'Back', meanings_path %>

app/views/meanings/index.html.erb
<p id="notice"><%= notice %></p>


<div class="container-90 mx-auto">
<h1>Meanings</h1>

<%= render "shared/table"%>
</div>

app/views/meanings/meaning_examples.html.erb
<div class="mx-auto container-90">
  <p>
  <strong>Meaning:</strong>
  <%= @meaning.meaning %>
</p>
<table class="table table-hover">
  <thead >
    <tr>
      <th>例文</th>
      <th>意味</th>
      <th colspan="3"></th>
      <th><%= submit_tag "単語帳に追加", class: "btn btn-primary" %></th>
    </tr>
  </thead>
  <tbody>
    <% @examples.each do |example| %>
      <tr>
        <td><%= example.sentence %></td>
        <td><%= example.translation %></td>

        <%= simple_form_for(@like) do |f|  %>
        <% if example.user.id == current_user.id %>
          <td><i class="fa fa-thumbs-up thumbs-uped" aria-hidden="true" data-toggle="tooltip" data-placement="right" title="あなたの投稿です">
          <%= Like.where(example_id: example.id).count %>
        </td>
        <% elsif Like.where(example_id: example.id).where(voter: current_user.id).exists? %>
          <td><i class="fa fa-thumbs-up thumbs-uped" aria-hidden="true" data-toggle="tooltip" data-placement="right" title="いいね済みです">
            <%= Like.where(example_id: example.id).count %>
        <% else %>
        <td>
          <%=  f.input :example_id, :as => :hidden, :input_html => { :value => example.id } %>
          <%=  f.input :user_id, :as => :hidden, :input_html => { :value => example.user.id } %>
          <%= button_tag(type: 'submit', class: "btn btn-link btn-thums-up") do %><i class="fa fa-thumbs-up" aria-hidden="true" data-toggle="tooltip" data-placement="right" title="ナイス"></i>
          <% end %>
          <span class="like-count"><%= Like.where(example_id: example.id).count %></span>
        </td>
        <% end %>
        <% end %>


      </tr>
    <% end %>
  </tbody>
</table>


<%= link_to 'Edit', edit_meaning_path(@meaning) %> |
<%= link_to 'Back', meanings_path %>

</div>

app/views/meanings/new.html.erb
<h1>New Meaning</h1>

<%= render 'form', meaning: @meaning %>

<%= link_to 'Back', meanings_path %>